# Generated by Django 3.0.6 on 2020-05-05 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut_usuario', models.CharField(max_length=12, unique=True, verbose_name='Rut Usuario')),
                ('primer_nombre', models.CharField(max_length=20, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=20, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('segundo_apellido', models.CharField(max_length=20, null=True, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('telefono', models.BigIntegerField(null=True, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[(1, 'Mesa de Ayuda'), (2, 'Liquidador'), (3, 'Personal Taller'), (4, 'Personal Grua')], max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('rut_asegurado', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('primer_nombre', models.CharField(max_length=20, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=20, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('segundo_apeliido', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('estado', models.CharField(default=1, max_length=1)),
                ('usuario_rut_usuario', models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSiniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Grua',
            fields=[
                ('patente_grua', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Patente Grúa')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='InformeDano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('perdida_total', models.CharField(blank=True, max_length=1, null=True, verbose_name='Perdida Total')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.CharField(default=1, max_length=1, verbose_name='Vigencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Termino')),
                ('estado', models.CharField(default=1, max_length=1)),
                ('asegurado_rut_asegurado', models.ForeignKey(db_column='asegurado_rut_asegurado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Asegurado', verbose_name='Rut Asegurado')),
            ],
        ),
        migrations.CreateModel(
            name='RegAsegurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('nombre_asegurado', models.CharField(max_length=30)),
                ('nro_poliza', models.IntegerField()),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=50)),
                ('cod_error', models.CharField(max_length=500)),
                ('mensaje', models.CharField(max_length=300)),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegGrua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('patente_grua', models.CharField(max_length=7)),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Región')),
            ],
        ),
        migrations.CreateModel(
            name='RegPoliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('nro_poliza', models.IntegerField()),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegSiniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('id_siniestro', models.IntegerField()),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('nombre_taller', models.CharField(max_length=30)),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registrador', models.CharField(max_length=30)),
                ('nombre_registrado', models.CharField(max_length=30)),
                ('fecha_hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SeveridadDano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre ')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('cobertura_max', models.IntegerField(verbose_name='Cobertura Máxima')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente_vehiculo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Patente')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('nro_motor', models.CharField(max_length=100, verbose_name='N° Motor')),
                ('asegurado_rut_asegurado', models.ForeignKey(db_column='asegurado_rut_asegurado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Asegurado', verbose_name='Rut Asegurado')),
                ('marca_id_marca', models.ForeignKey(db_column='marca_id_marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Marca', verbose_name='ID Marca')),
                ('tipo_vehiculo_id_tipo_auto', models.ForeignKey(db_column='tipo_vehiculo_id_tipo_auto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.TipoVehiculo', verbose_name='Tipo Vehículo')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Taller')),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('capacidad_taller', models.IntegerField(verbose_name='Capacidad Taller')),
                ('estado', models.CharField(default=1, max_length=1, verbose_name='Estado')),
                ('estado_delete', models.CharField(default=1, max_length=1)),
                ('usuario_rut_usuario', models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hr', models.DateField(verbose_name='Fecha Siniestro')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('parte_policial', models.FileField(blank=True, null=True, upload_to='', verbose_name='Parte Policial')),
                ('foto_licencia', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Licencia')),
                ('est_siniestro_id_est_siniestro', models.ForeignKey(db_column='est_siniestro_id_est_siniestro', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.EstadoSiniestro', verbose_name='Estado Siniestro')),
                ('grua_patente_grua', models.ForeignKey(blank=True, db_column='grua_patente_grua', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Grua', verbose_name='Patente Grúa')),
                ('poliza_id_poliza', models.ForeignKey(db_column='poliza_id_poliza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Poliza', verbose_name='ID Póliza')),
                ('taller_id_taller', models.ForeignKey(db_column='taller_id_taller', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Taller', verbose_name='Taller')),
                ('tipo_accidente_id_tipo_acc', models.ForeignKey(db_column='tipo_accidente_id_tipo_acc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.TipoAccidente', verbose_name='Tipo Accidente')),
                ('usuario_rut_usuario', models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioGrua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('usuario_rut_usuario', models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField(verbose_name='Fecha')),
                ('valor_total', models.IntegerField(verbose_name='Valor Total')),
                ('estado_id_est_presupuesto', models.ForeignKey(db_column='estado_id_est_presupuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.EstadoPresupuesto', verbose_name='ID Est. Presupuesto')),
                ('informe_dano_id_info_dano', models.ForeignKey(db_column='informe_dano_id_info_dano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.InformeDano', verbose_name='ID Inf. Daño')),
                ('usuario_rut_usuario', models.ForeignKey(blank=True, db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo_patente_vehiculo',
            field=models.ForeignKey(db_column='vehiculo_patente_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Vehiculo', verbose_name='Patente Vehículo'),
        ),
        migrations.CreateModel(
            name='PlanSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducible', models.IntegerField(verbose_name='Deducible')),
                ('poliza_id_poliza', models.ForeignKey(db_column='poliza_id_poliza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Poliza', verbose_name='ID Póliza')),
                ('tipo_plan_id_tip_plan', models.ForeignKey(db_column='tipo_plan_id_tip_plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.TipoPlan', verbose_name='Tipo Plan')),
            ],
        ),
        migrations.AddField(
            model_name='informedano',
            name='severidad_dano_id_seve_dano',
            field=models.ForeignKey(db_column='severidad_dano_id_seve_dano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.SeveridadDano', verbose_name='Severidad Daño'),
        ),
        migrations.AddField(
            model_name='informedano',
            name='siniestro_id',
            field=models.ForeignKey(db_column='siniestro_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Siniestro', verbose_name='ID Siniestro'),
        ),
        migrations.AddField(
            model_name='informedano',
            name='taller_id_taller',
            field=models.ForeignKey(db_column='taller_id_taller', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Taller', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='informedano',
            name='tipo_dano_id_tipo_dano',
            field=models.ForeignKey(db_column='tipo_dano_id_tipo_dano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.TipoDano', verbose_name='Tipo Daño'),
        ),
        migrations.AddField(
            model_name='informedano',
            name='usuario_rut_usuario',
            field=models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario'),
        ),
        migrations.AddField(
            model_name='informedano',
            name='vehiculo_patente_vehiculo',
            field=models.ForeignKey(db_column='vehiculo_patente_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Vehiculo', verbose_name='Patente Vehículo'),
        ),
        migrations.AddField(
            model_name='grua',
            name='servicio_grua_id_servicio',
            field=models.ForeignKey(db_column='servicio_grua_id_servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ServicioGrua', verbose_name='Servicio Grúa'),
        ),
        migrations.AddField(
            model_name='grua',
            name='usuario_rut_usuario',
            field=models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario'),
        ),
        migrations.CreateModel(
            name='FormularioActa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('siniestro_id', models.ForeignKey(db_column='siniestro_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Siniestro', verbose_name='ID Siniestro')),
                ('taller_id_taller', models.ForeignKey(db_column='taller_id_taller', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Taller', verbose_name='Taller')),
                ('tipo_acta_id_tipo_acta', models.ForeignKey(db_column='tipo_acta_id_tipo_acta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.TipoActa', verbose_name='Tipo Acta')),
                ('usuario_rut_usuario', models.ForeignKey(db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='N°')),
                ('asegurado_rut_asegurado', models.ForeignKey(blank=True, db_column='asegurado_rut_asegurado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Asegurado', verbose_name='Asegurado')),
                ('comuna_id_comuna', models.ForeignKey(db_column='comuna_id_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Comuna', verbose_name='Comuna')),
                ('servicio_grua_id_servicio', models.ForeignKey(blank=True, db_column='servicio_grua_id_servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ServicioGrua', verbose_name='Servicio GRúa')),
                ('siniestro_id', models.ForeignKey(blank=True, db_column='siniestro_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Siniestro', verbose_name='ID Siniestro')),
                ('taller_id_taller', models.ForeignKey(blank=True, db_column='taller_id_taller', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Taller', verbose_name='Taller')),
                ('usuario_rut_usuario', models.ForeignKey(blank=True, db_column='usuario_rut_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Rut Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_nro_region',
            field=models.ForeignKey(db_column='region_nro_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Region', verbose_name='Región'),
        ),
    ]
