# Generated by Django 3.0.6 on 2020-05-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='asegurado_rut_asegurado',
            field=models.ForeignKey(db_column='asegurado_rut_asegurado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Asegurado', verbose_name='Rut Asegurado'),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='formularioacta',
            name='fecha_hora',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_hr',
            field=models.DateField(auto_now=True, verbose_name='Fecha Siniestro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Mesa de Ayuda'), ('2', 'Liquidador'), ('3', 'Personal Taller'), ('4', 'Personal Grua')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9, null=True, verbose_name='Teléfono'),
        ),
    ]
