# Generated by Django 3.0.5 on 2020-04-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200427_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asegurado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estadopresupuesto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estadosiniestro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formularioacta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grua',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='informedano',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planseguro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='serviciogrua',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='severidaddano',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='siniestro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoacta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipodano',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoplan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'managed': False},
        ),
    ]
