# Generated by Django 3.0.5 on 2020-04-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200427_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asegurado',
            options={'managed': False, 'verbose_name_plural': 'Asegurados'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False, 'verbose_name_plural': 'Comuna'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': False, 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='estadopresupuesto',
            options={'managed': False, 'verbose_name_plural': 'Estado Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='estadosiniestro',
            options={'managed': False, 'verbose_name_plural': 'Estado Siniestros'},
        ),
        migrations.AlterModelOptions(
            name='formularioacta',
            options={'managed': False, 'verbose_name_plural': 'Formulario Actas'},
        ),
        migrations.AlterModelOptions(
            name='grua',
            options={'managed': False, 'verbose_name_plural': 'Grúas'},
        ),
        migrations.AlterModelOptions(
            name='informedano',
            options={'managed': False, 'verbose_name_plural': 'Informe Daños'},
        ),
        migrations.AlterModelOptions(
            name='planseguro',
            options={'managed': False, 'verbose_name_plural': 'Plan Seguros'},
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'managed': False, 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'managed': False, 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False, 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='serviciogrua',
            options={'managed': False, 'verbose_name_plural': 'Servicios Grúas'},
        ),
        migrations.AlterModelOptions(
            name='severidaddano',
            options={'managed': False, 'verbose_name_plural': 'Severidad Daños'},
        ),
        migrations.AlterModelOptions(
            name='siniestro',
            options={'managed': False, 'verbose_name_plural': 'Siniestros'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'managed': False, 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={'managed': False, 'verbose_name_plural': 'Tipo Accidentes'},
        ),
        migrations.AlterModelOptions(
            name='tipoacta',
            options={'managed': False, 'verbose_name_plural': 'Tipo Actas'},
        ),
        migrations.AlterModelOptions(
            name='tipodano',
            options={'managed': False, 'verbose_name_plural': 'Tipo Daños'},
        ),
        migrations.AlterModelOptions(
            name='tipoplan',
            options={'managed': False, 'verbose_name_plural': 'Tipo Planes'},
        ),
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'managed': False, 'verbose_name_plural': 'Tipo Vehículo'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'managed': False, 'verbose_name_plural': 'Vehículos'},
        ),
    ]
