# Generated by Django 3.0.6 on 2020-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200528_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(max_length=11, verbose_name='Teléfono'),
        ),
    ]
