# Generated by Django 3.0.6 on 2020-06-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200529_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='taller_id_taller',
            field=models.ForeignKey(db_column='taller_id_taller', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Taller', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='rut_asegurado',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='informedano',
            name='fecha_hora',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='informedano',
            name='observaciones',
            field=models.CharField(max_length=1024, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='foto_licencia',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos Licencias'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='parte_policial',
            field=models.ImageField(blank=True, null=True, upload_to='Partes Policiales'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='capacidad_taller',
            field=models.CharField(max_length=3, verbose_name='Capacidad Taller'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(max_length=10, unique=True, verbose_name='Rut Usuario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
    ]
