# Generated by Django 3.0.5 on 2020-04-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asegurado',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='EstadoPresupuesto',
        ),
        migrations.DeleteModel(
            name='EstadoSiniestro',
        ),
        migrations.DeleteModel(
            name='FormularioActa',
        ),
        migrations.DeleteModel(
            name='Grua',
        ),
        migrations.DeleteModel(
            name='InformeDano',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='PlanSeguro',
        ),
        migrations.DeleteModel(
            name='Poliza',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='RegAsegurado',
        ),
        migrations.DeleteModel(
            name='RegError',
        ),
        migrations.DeleteModel(
            name='RegGrua',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RegPoliza',
        ),
        migrations.DeleteModel(
            name='RegSiniestro',
        ),
        migrations.DeleteModel(
            name='RegTaller',
        ),
        migrations.DeleteModel(
            name='RegUsuario',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='ServicioGrua',
        ),
        migrations.DeleteModel(
            name='SeveridadDano',
        ),
        migrations.DeleteModel(
            name='Siniestro',
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
        migrations.DeleteModel(
            name='TipoAccidente',
        ),
        migrations.DeleteModel(
            name='TipoActa',
        ),
        migrations.DeleteModel(
            name='TipoDano',
        ),
        migrations.DeleteModel(
            name='TipoPlan',
        ),
        migrations.DeleteModel(
            name='TipoVehiculo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
